
server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/frap97?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: frap97
        password: Frank1597!!
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect